### PR TITLE
Upgrading back-end to ruby version 2.5.0

### PR DESCRIPTION
**Pull request by jarl-borg**
Completing the upgrade to ruby 2.5.0. 

[TRELLO CARD](https://trello.com/c/4VXNyn2c/2107-tariff17-update-the-versions-of-ruby-used-in-the-apps-to-250)

Last problem I encountered was this :

screen shot 2018-02-09 at 4 57 14 pm

When all tests were passing but the old gem did not know how to handle the encoding so I patch it on the forked repo to be used by all 3 apps here :

https://github.com/bitzesty/simplecov-rcov

### CODE REVIEW

**Comment by jarl-borg** [comment]
I don't have the access to the synk to see the security issues

**Comment by jarl-borg** [comment]
also don't have the access to circle CI @matthewford

**Comment by rusllonrails** [comment]
try to add `libssl1.0-dev` into `.circleci/config.yml` config file:
`sudo apt-get update -qq && sudo apt-get install -y build-essential postgresql libpq-dev nodejs rake`
to:
`sudo apt-get update -qq && sudo apt-get install -y build-essential postgresql libpq-dev nodejs rake libssl1.0-dev`

**Comment by jarl-borg** [comment]
Still unable to see issue in snyk 

screen shot 2018-02-09 at 5 03 05 pm

**Pull request merged**
