### PR TITLE
Migration to Postgresql 

### PR DESCRIPTION
**Pull request by theharq**
#### What this PR does:

This PR is the first attempt to migrate the tariff backend from using a mysql database to postgresql.

#### Notes

This project depends on many queries crafted by `hand` for mysql, but many of them are not compatible with newer versions or portgresql.

For example newer versions of MySQL or Postgres do not allow use invalid sql queries using nonaggregated columns not listed in the `group by`.. but this was valid in the version 5.5

> MySQL extends the standard SQL use of GROUP BY so that the select list can refer to nonaggregated columns not named in the GROUP BY clause. This means that the preceding query is legal in MySQL. You can use this feature to get better performance by avoiding unnecessary column sorting and grouping. However, this is useful primarily when all values in each nonaggregated column not named in the GROUP BY are the same for each group. The server is free to choose any value from each group, so unless they are the same, the values chosen are indeterminate.

https://dev.mysql.com/doc/refman/5.5/en/group-by-handling.html

So it happens that some queries `work` in the actual version used.. but they are invalid SQL queries, and because of this there are `false positives` in different tests of the application.

In order to avoid breaking non tested logic, I had to run these queries against a mysql 5.5 db, check the results and try to understand what mysql is interpreting.. then.. generate a new valid sql query.

Sometimes we can see in the console suggestions of adding a new column to the `GROUP BY` expression, but this is not a fix per se, all the cases have to be reviewed because the results will be different.

**Update**

All tests green, no postgresql migration pending tests :+1:

### CODE REVIEW

**Comment by theharq** [comment]
cc @matthewford @macool

**Comment by matthewford** [comment]
@theharq needs rebasing

**Comment by theharq** [comment]
:ok_hand:

**Comment by theharq** [comment]
The PR is green again :ok_hand:

**Comment by theharq** [comment]
thanks!

**Pull request merged**
