### PR TITLE
Prevent sending more than 1 email per day

### PR DESCRIPTION
**Pull request by theharq**
#### What this PR does:

This is a workaround to have a flag that will be switch until the end of the day.

Currently calling these methods triggers an email, and since the sync process runs every hour an email is sent every hour.

This change takes advantage of the low level caching system to invalidate after certain amount of time.

We cannot persist the state of the email sent in the db because none of this cases are for a specific tariff update.

### CODE REVIEW

**Comment by theharq** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;DpUPHjw8&#x2F;207-tariff16-for-each-email-add-in-a-boolean-to-say-if-it-was-sent-today-or-not"> [TARIFF16] For each email add in a boolean to say if it was sent today or not</a>

**Comment by matthewford** [comment]
@theharq technically the sync schedule is like 8pm -> 8am, so end of day cache might not work

**Comment by theharq** [comment]
I see.. so our workers runs every hour from 00:00 to 09:00 and then.. from 18:00 to 23:00

maybe caching only for 9 hours?  maybe 12 hours?

**Comment by theharq** [comment]
Closing this PR since this is no longer an issue

**Pull request closed without merging**
